export const FINANCIAL_TERMS = {
  pnl: "Profit and loss: the net amount gained or lost over the selected period.",
  equity: "The current total value of the portfolio, including cash and open positions.",
  winRate: "The percentage of completed trades that closed with a profit.",
  portfolioHeat: "The estimated share of portfolio capital at risk if every active stop is reached.",
  drawdown: "The percentage decline from the portfolio's previous peak value.",
  breaker: "A safety rule that blocks new risk after a configured loss or drawdown limit is reached.",
  correlationPenalty: "Extra risk assigned when several positions tend to move together, making diversification less effective.",
  exposure: "How much portfolio capital is affected by a ticker, sector, asset class, or trade direction.",
  marketRegime: "A description of the current market environment, such as trending, volatile, or risk-off.",
  timeframeAgreement: "How consistently the signal direction appears across daily, four-hour, and one-hour data.",
  halfKelly: "A conservative position-sizing method that uses half of the Kelly Criterion recommendation.",
  confidence: "The model's estimated strength or probability for a signal, based on available evidence.",
  calibration: "A check that confidence scores match real outcomes—for example, 70% signals succeeding about 70% of the time.",
  oos: "Out-of-sample: market data kept separate from model selection and used only for a more realistic final test.",
  sharpe: "Risk-adjusted return measured against total volatility. Higher values generally indicate more return per unit of risk.",
  sortino: "Risk-adjusted return measured against harmful downside volatility rather than all price movement.",
  profitFactor: "Gross profit divided by gross loss. A value above 1 means profits exceeded losses.",
  maxDrawdown: "The largest peak-to-trough decline during the measured period.",
  expectancy: "The average expected gain or loss per trade, including both wins and losses.",
  slippage: "The difference between the expected trade price and the price where the order actually fills.",
  spread: "The gap between the best available buy and sell prices.",
  bps: "Basis points. One basis point equals 0.01%, so 100 bps equals 1%.",
  atr: "Average True Range: a measure of typical price movement used to estimate volatility and stop distance.",
  ema: "Exponential Moving Average: a trend measure that gives more weight to recent prices.",
  rsi: "Relative Strength Index: a 0–100 momentum measure often used to identify overbought or oversold conditions.",
  mfe: "Maximum Favorable Excursion: the largest unrealized profit reached while a trade was open.",
  mae: "Maximum Adverse Excursion: the largest unrealized loss reached while a trade was open.",
  reconciliation: "A consistency check confirming that orders, fills, cash, positions, and reported totals agree.",
  rewardRisk: "Potential net profit divided by the planned loss if the stop is reached.",
  timeStop: "A rule to exit a trade after a set time if the expected move has not occurred.",
  stressTest: "A hypothetical portfolio result under a sharp market move, such as stocks falling 5%.",
  reservedCash: "Cash set aside for pending buy orders and unavailable for other orders until released.",
  regime: "The current market environment, described by trend, volatility, breadth, and risk appetite.",
} as const;

export type FinancialTerm = keyof typeof FINANCIAL_TERMS;
